### ISSUE TITLE
Lenguaje en ingles

### ISSUE THREAD

**Issue by AnglDavd** [maxedrom/ThemeSplat_Extensions_SP#2]
[sitesplat.zip](https://github.com/maxedrom/ThemeSplat_Extensions_SP/files/3342379/sitesplat.zip)

acá te dejo los archivos en ingles de los addons que tengo

**Comment by maxedrom** [comment]
Gracias, ya actualice unos cuantos. Voy a seguir.. se voy lento.

**Comment by maxedrom** [comment]
Gracias
